import executive_engine_api as api

def runMission():
    # api.activateBehavior('SELF_LOCALIZE_BY_ODOMETRY')
    api.activateBehavior('SELF_LOCALIZE_BY_VISUAL_MARKER')
    api.executeBehavior('TAKE_OFF')
    # api.inhibitBehavior('SELF_LOCALIZE_BY_ODOMETRY')

    # api.activateBehavior('SELF_LOCALIZE_BY_VISUAL_MARKER')
    api.executeBehavior('GO_TO_POINT', coordinates=[0, -1.3, 1.3])
    api.executeBehavior('GO_TO_POINT', coordinates=[3.4, -1.3, 1.3])
    # api.executeBehavior('GO_TO_POINT', coordinates=[3, -1.3, 1.3])
    # api.executeBehavior('GO_TO_POINT', coordinates=[5.5, -0.6, 1.3])
    # api.executeBehavior('GO_TO_POINT', coordinates=[7.6, 0.3, 1.3])
    # api.executeBehavior('ROTATE', angle=90)
    api.executeBehavior('ROTATE', angle=180)
    # api.executeBehavior('GO_TO_POINT', coordinates=[7.5, -1.5, 1.3])
    # api.executeBehavior('ROTATE', angle=135)
    # api.executeBehavior('GO_TO_POINT', coordinates=[7.5, -3.5, 1.8])
    # api.executeBehavior('ROTATE', angle=90)
    # api.executeBehavior('GO_TO_POINT', coordinates=[10.5, -4.2, 1.8])
    # api.executeBehavior('GO_TO_POINT', coordinates=[3.75, 0.6, 1.3])
    # api.executeBehavior('GO_TO_POINT', coordinates=[0, 0.6, 1.3])
    # api.executeBehavior('GO_TO_POINT', coordinates=[10.5, -3.5, 1.3])
    api.executeBehavior('GO_TO_POINT', coordinates=[3.4, -1.3, 1.3])
    api.executeBehavior('GO_TO_POINT', coordinates=[0, -1.3, 1.3])
    api.executeBehavior('GO_TO_POINT', coordinates=[0, 0, 2])
    # api.executeBehavior('ROTATE', angle=90)
    # api.executeBehavior('ROTATE', angle=0)
    # api.executeBehavior('GO_TO_POINT', coordinates=[0, 0, 1.5])
    api.executeBehavior('LAND_ON_STATIC_PLATFORM')
    api.inhibitBehavior('SELF_LOCALIZE_BY_VISUAL_MARKER')

    # api.inhibitBehavior('SELF_LOCALIZE_BY_ODOMETRY')
    api.executeBehavior('LAND')
